import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { ArrowLeftFromLineIcon } from "lucide-react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} min-h-screen antialiased bg-neutral-950 text-neutral-100 flex flex-col`}
      >
        <div className="p-2">
          <Link href="/" className="flex gap-2 items-center font-bold">
            <ArrowLeftFromLineIcon className="h-5 w-5" /> All Tools
          </Link>
        </div>
        <div className="flex h-full flex-grow">{children}</div>
      </body>
    </html>
  );
}
